from __future__ import annotations

UNIX_ITEMS: list[dict[str, str]] = [
    {"item_id": "U-01", "title": "root 계정 원격 접속 제한", "category": "계정 관리", "severity": "high"},
    {"item_id": "U-02", "title": "비밀번호 관리정책 설정", "category": "계정 관리", "severity": "high"},
    {"item_id": "U-03", "title": "계정 잠금 임계값 설정", "category": "계정 관리", "severity": "high"},
    {"item_id": "U-04", "title": "비밀번호 파일 보호", "category": "계정 관리", "severity": "high"},
    {"item_id": "U-05", "title": "root 이외의 UID가 ‘0’ 금지", "category": "계정 관리", "severity": "high"},
    {"item_id": "U-06", "title": "사용자 계정 su 기능 제한", "category": "계정 관리", "severity": "high"},
    {"item_id": "U-07", "title": "불필요한 계정 제거", "category": "계정 관리", "severity": "low"},
    {"item_id": "U-08", "title": "관리자 그룹에 최소한의 계정 포함", "category": "계정 관리", "severity": "medium"},
    {"item_id": "U-09", "title": "계정이 존재하지 않는 GID 금지", "category": "계정 관리", "severity": "low"},
    {"item_id": "U-10", "title": "동일한 UID 금지", "category": "계정 관리", "severity": "medium"},
    {"item_id": "U-11", "title": "사용자 Shell 점검", "category": "계정 관리", "severity": "low"},
    {"item_id": "U-12", "title": "세션 종료 시간 설정", "category": "계정 관리", "severity": "low"},
    {"item_id": "U-13", "title": "안전한 비밀번호 암호화 알고리즘 사용", "category": "계정 관리", "severity": "medium"},
    {"item_id": "U-14", "title": "root 홈, 패스 디렉터리 권한 및 패스 설정", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-15", "title": "파일 및 디렉터리 소유자 설정", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-16", "title": "/etc/passwd 파일 소유자 및 권한 설정", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-17", "title": "시스템 시작 스크립트 권한 설정", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-18", "title": "/etc/shadow 파일 소유자 및 권한 설정", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-19", "title": "/etc/hosts 파일 소유자 및 권한 설정", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-20", "title": "/etc/(x)inetd.conf 파일 소유자 및 권한 설정", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-21", "title": "/etc/(r)syslog.conf 파일 소유자 및 권한 설정", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-22", "title": "/etc/services 파일 소유자 및 권한 설정", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-23", "title": "SUID, SGID, Sticky bit 설정 파일 점검", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-24", "title": "사용자, 시스템 환경변수 파일 소유자 및 권한 설정", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-25", "title": "world writable 파일 점검", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-26", "title": "/dev에 존재하지 않는 device 파일 점검", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-27", "title": "$HOME/.rhosts, hosts.equiv 사용 금지", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-28", "title": "접속 IP 및 포트 제한", "category": "파일 및 디렉토리 관리", "severity": "high"},
    {"item_id": "U-29", "title": "hosts.lpd 파일 소유자 및 권한 설정", "category": "파일 및 디렉토리 관리", "severity": "low"},
    {"item_id": "U-30", "title": "UMASK 설정 관리", "category": "파일 및 디렉토리 관리", "severity": "medium"},
    {"item_id": "U-31", "title": "홈 디렉토리 소유자 및 권한 설정", "category": "파일 및 디렉토리 관리", "severity": "medium"},
    {"item_id": "U-32", "title": "홈 디렉토리로 지정한 디렉토리의 존재 관리", "category": "파일 및 디렉토리 관리", "severity": "medium"},
    {"item_id": "U-33", "title": "숨겨진 파일 및 디렉토리 검색 및 제거", "category": "파일 및 디렉토리 관리", "severity": "low"},
    {"item_id": "U-34", "title": "Finger 서비스 비활성화", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-35", "title": "공유 서비스에 대한 익명 접근 제한 설정", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-36", "title": "r 계열 서비스 비활성화", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-37", "title": "crontab 설정파일 권한 설정 미흡", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-38", "title": "DoS 공격에 취약한 서비스 비활성화", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-39", "title": "불필요한 NFS 서비스 비활성화", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-40", "title": "NFS 접근 통제", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-41", "title": "불필요한 automountd 제거", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-42", "title": "불필요한 RPC 서비스 비활성화", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-43", "title": "NIS, NIS+ 점검", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-44", "title": "tftp, talk 서비스 비활성화", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-45", "title": "메일 서비스 버전 점검", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-46", "title": "일반 사용자의 메일 서비스 실행 방지", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-47", "title": "스팸 메일 릴레이 제한", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-48", "title": "expn, vrfy 명령어 제한", "category": "서비스 관리", "severity": "medium"},
    {"item_id": "U-49", "title": "DNS 보안 버전 패치", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-50", "title": "DNS Zone Transfer 설정", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-51", "title": "DNS 서비스의 취약한 동적 업데이트 설정 금지", "category": "서비스 관리", "severity": "medium"},
    {"item_id": "U-52", "title": "Telnet 서비스 비활성화", "category": "서비스 관리", "severity": "medium"},
    {"item_id": "U-53", "title": "FTP 서비스 정보 노출  제한", "category": "서비스 관리", "severity": "low"},
    {"item_id": "U-54", "title": "암호화되지 않는 FTP 서비스 비활성화", "category": "서비스 관리", "severity": "medium"},
    {"item_id": "U-55", "title": "FTP 계정 Shell 제한", "category": "서비스 관리", "severity": "medium"},
    {"item_id": "U-56", "title": "FTP 서비스 접근 제어 설정", "category": "서비스 관리", "severity": "low"},
    {"item_id": "U-57", "title": "Ftpusers 파일 설정", "category": "서비스 관리", "severity": "medium"},
    {"item_id": "U-58", "title": "불필요한 SNMP 서비스 구동 점검", "category": "서비스 관리", "severity": "medium"},
    {"item_id": "U-59", "title": "안전한 SNMP 버전 사용", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-60", "title": "SNMP Community String 복잡성 설정", "category": "서비스 관리", "severity": "medium"},
    {"item_id": "U-61", "title": "SNMP Access Control 설정", "category": "서비스 관리", "severity": "high"},
    {"item_id": "U-62", "title": "로그인 시 경고 메시지 설정", "category": "서비스 관리", "severity": "low"},
    {"item_id": "U-63", "title": "sudo 명령어 접근 관리", "category": "서비스 관리", "severity": "medium"},
    {"item_id": "U-64", "title": "주기적 보안 패치 및 벤더 권고사항 적용", "category": "패치 관리", "severity": "high"},
    {"item_id": "U-65", "title": "NTP 및 시각 동기화 설정", "category": "로그 관리", "severity": "medium"},
    {"item_id": "U-66", "title": "정책에 따른 시스템 로깅 설정", "category": "로그 관리", "severity": "medium"},
    {"item_id": "U-67", "title": "로그 디렉터리 소유자 및 권한 설정", "category": "로그 관리", "severity": "medium"},
]

UNIX_ITEM_IDS = [item["item_id"] for item in UNIX_ITEMS]
UNIX_ITEM_TITLES = {item["item_id"]: item["title"] for item in UNIX_ITEMS}
UNIX_ITEM_BY_ID = {item["item_id"]: item for item in UNIX_ITEMS}

UNIX_PARTIAL_ITEM_IDS = {
    "U-01",
    "U-02",
    "U-03",
    "U-04",
    "U-05",
    "U-06",
    "U-12",
    "U-13",
    "U-14",
    "U-16",
    "U-18",
    "U-30",
    "U-34",
    "U-36",
    "U-37",
    "U-39",
    "U-40",
    "U-42",
    "U-44",
    "U-52",
    "U-54",
    "U-58",
    "U-62",
    "U-63",
    "U-64",
    "U-65",
    "U-66",
    "U-67",
}
